spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: auction-service
          uri: http://localhost:8084
          predicates:
            - Path=/auction/**,/bid/**,/watchlist/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**
