spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: apmcDB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
project:
  image: /images
