spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mohammadarqham182002@gmail.com
    password: vxapmozqhyisdaoe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: mail-service
  config:
    import: "optional:configserver:http://localhost:8088"


