spring:
  application:
    name: auction-service
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: apmcDB
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  main:
    allow-circular-references: true


